#!/bin/bash
if [ $# -eq 0 ]; then
  echo "No file supplied"
  echo "Usage: run <filename>"
  exit
fi
fullname=$1
file_ext=${fullname##*.}
length=$(($#0))
arguments=${@:2:length}
if [ $file_ext = "py" ]; then
  python $fullname $arguments
elif [ $file_ext = "cpp" ] || [ $file_ext = "cc" ]; then
  cpp_executable_ext='.out'
  output_file=${fullname%.*}
  g++ -o $output_file$cpp_executable_ext $fullname
  ./$output_file$cpp_executable_ext $arguments
  rm $output_file$cpp_executable_ext
elif [ $file_ext = "js" ]; then
  node $fullname $arguments
elif [ $file_ext = "c" ]; then
  c_executable_ext='.out'
  output_file=${fullname%.*}
  gcc -o $output_file$c_executable_ext $fullname
  ./$output_file$c_executable_ext $arguments
  rm $output_file$c_executable_ext
fi
