#!/bin/bash

# Variables to change color of text
NORMAL=$(tput sgr0)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2; tput bold)

OLDIFS=$IFS

IFS=$(echo -en "\n\b")

# close the program
quit() {
  exit
}

# quit if no arguments
if [ $# -eq 0 ]; then
  echo "$YELLOW[Warning]$NORMAL No file supplied"
  echo "Usage: run <filename> <arguments>"
  echo "Example: run multiply.cpp 5 6"
  quit
fi

fullname=$1
file_ext=${fullname##*.}

# Exit if the file has no extension
if [ $fullname == $file_ext ]; then
  echo "File with no extension cannot be passed"
  quit
fi

# restore field seperator
IFS=$OLDIFS

#Copy all the arguments in the array 'arguments'
i=0
declare -a arguments;
for var in "${@:2}"
do
  arguments[i]=$var
  i=$(($i+1))
done

#Extension based search for which command to execute
if [ $file_ext = "py" ]; then
  python "$fullname" "${arguments[@]}"
elif [ $file_ext = "cpp" ] || [ $file_ext = "cc" ]; then
  cpp_executable_ext='.out'
  output_file=${fullname%.*}
  g++ -o "$output_file$cpp_executable_ext" "$fullname"
  if [ $? -ne 0 ]; then
    quit
  fi
  trap "rm $output_file$cpp_executable_ext && quit" 2
  ./"$output_file$cpp_executable_ext" "${arguments[@]}"
  rm "$output_file$cpp_executable_ext"
elif [ $file_ext = "js" ]; then
  node "$fullname" "${arguments[@]}"
elif [ $file_ext = "rb" ]; then
  ruby "$fullname" "${arguments[@]}"
elif [ $file_ext = "sh" ]; then
  sh "$fullname" "${arguments[@]}"
elif [ $file_ext = "zsh" ]; then
  zsh "$fullname" "${arguments[@]}"
elif [ $file_ext = "php" ]; then
  php "$fullname" "${arguments[@]}"
elif [ $file_ext = "java" ]; then
  java_class_ext='.class'
  filename=${fullname%.*}
  javac "$fullname"
  if [ $? -ne 0 ]; then
    quit
  fi
  java "$filename" "${arguments[@]}"
  rm "$filename$java_class_ext"
elif [ $file_ext = "c" ]; then
  c_executable_ext='.out'
  output_file=${fullname%.*}
  gcc -o "$output_file$c_executable_ext" "$fullname"
  if [ $? -ne 0]; then
    quit
  fi
  trap "rm $output_file$c_executable_ext && quit" 2
  ./"$output_file$c_executable_ext" "${arguments[@]}"
  rm "$output_file$c_executable_ext"
fi